# Generated by Django 5.0.6 on 2024-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='tipo_corte',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='correo_cliente',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_cita',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_cliente',
            field=models.CharField(default='Nombre Predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono_cliente',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='cita',
            name='barbero',
            field=models.CharField(default='Barbero Predeterminado', max_length=100),
        ),
    ]
