# Generated by Django 5.0.6 on 2024-06-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_cita_duracion_remove_cita_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='correo_cliente',
            new_name='email_cliente',
        ),
        migrations.AddField(
            model_name='cita',
            name='apellido_cliente',
            field=models.CharField(default='Apellido Predeterminado', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='edad_cliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
